name: Generate Snake Animation

on:
  schedule:
    - cron: "* * * * *"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate Snake
      uses: Platane/snk@master
      with:
        github_user_name: CarolinaTC
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
